openapi: 3.0.0
servers:
  - url: "https://dashboard.getporter.dev"
info:
  description: |
    # Introduction

    Welcome to the documentation for Porter's API. Our public API is still a
    work-in-progress, although all endpoints prefixed with `/api/v1` will remain
    stable. 


    To begin using the Porter API, API tokens must be enabled for your Porter
    project. If API tokens are enabled, you will see the following in the
    project settings page:

    <br />


    Nearly all endpoints will have the following structure:



    ```yaml
    /api/v1/projects/{project_id}/[resources]
    ```



    For example, creating a new release (which exists inside a cluster and
    namespace) has the following endpoint:



    ```yaml
    POST /api/v1/projects/1/clusters/1/namespaces/default/releases
    ```

    All resources are by default pluralized (i.e. `releases` instead of
    `release`). The API supports the following HTTP Verbs:

    - `GET`
    - `POST`
    - `PUT`
    - `PATCH`
    - `DELETE`

    API design is based on the following actions:

    - List — lists a group of resources
    - Get — retrieves a single resource
    - Create — creates a new resource
    - Update — updates an existing resource
    - Delete — deletes an existing resource

    # Authorization

    Requests are authenticated via a JWT token that can be obtained from the dashboard in **Project Settings:**

    ![image](https://imagedelivery.net/l4LYM_vOYKe7O1NCT_Nc_g/30748e55-35a9-478e-f5a9-fbe126099d00/large)

    JWT tokens are signed via an `HMAC-SHA` algorithm. All API tokens are **project-scoped**, other actions that are outside the scope of a project will need to be performed using a personal access token. 

    <SecurityDefinitions />

    **Basic Roles**

    For ease of use, each API token can be granted one of three roles: admin, developer, or viewer. A token with admin permissions can read or write to any resource in the project, a token with developer permissions can read or write to any resource *except* settings (only read for settings), and a token with viewer permissions can view all resources within the project *except* settings.

    **Custom Roles** 

    API tokens can be assigned custom roles based on a set of custom **policies**. These policies can be created from the dashboard or the API. From the dashboard, when you create a custom policy, you can select the resources that you would like the role to access:

    ![image](https://imagedelivery.net/l4LYM_vOYKe7O1NCT_Nc_g/84af3259-4ef2-4e9d-4319-563d61fb4300/large)

    Each policy refers to various **scopes** within a project. These scopes are the following:

    ```yaml
    Project
    -- Cluster
    -- -- Namespace
    -- -- -- Application
    -- Infra
    -- Settings
    -- Registry
    -- Helm Repository
    -- Git Installation
    ```

    For each scope, a set of allowed **actions** can be granted.
  version: 1.0.0
  title: API v1
  termsOfService: "https://docs.porter.run/terms-and-privacy/terms-of-service/"
  contact:
    name: Porter Support
    email: support@porter.run
tags:
  - name: Namespaces
    description: >
      Namespaces are a Kubernetes concept which divides resources in the cluster into 
      separate logical groups. Each Kubernetes cluster comes with a `default` namespace, 
      and typically a `kube-system` namespace which contains services which help Kubernetes run.
  - name: Releases
    description: Porter Releases
  - name: Registries
    description: Porter Registries
  - name: Stacks
    description: Porter Stacks 
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  links: {}
  callbacks: {}
security:
  - Bearer: []